[build]
  command = "npm run build"
  publish = "out"
  base = "frontend"

[build.environment]
  NEXT_PUBLIC_API_URL = "https://p2p-book-exchange-backend.onrender.com/api"
  NODE_VERSION = "18"
  NPM_FLAGS = "--legacy-peer-deps"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self' https://p2p-book-exchange-backend.onrender.com https://images.unsplash.com; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; font-src 'self' https://fonts.gstatic.com; img-src 'self' data: https://p2p-book-exchange-backend.onrender.com https://images.unsplash.com;" 